# Generated by Django 3.1.3 on 2020-11-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=64)),
                ('dt', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('img', models.CharField(max_length=32)),
                ('owner', models.CharField(max_length=32)),
            ],
        ),
    ]
