# Generated by Django 3.1.3 on 2020-11-06 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_auto_20201105_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 15, 16, 48, 633749)),
        ),
        migrations.AlterField(
            model_name='function',
            name='img',
            field=models.CharField(default='Wait', max_length=32),
        ),
    ]
