# Generated by Django 3.1.3 on 2020-11-06 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_auto_20201106_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='img',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='function',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
