# Generated by Django 3.1.3 on 2020-11-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_auto_20201106_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='img',
            field=models.TextField(max_length=32, null=True),
        ),
    ]
