# Generated by Django 3.1.3 on 2020-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0006_auto_20201107_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='img_alt',
            field=models.TextField(null=True),
        ),
    ]
