# Generated by Django 3.1.3 on 2020-11-07 19:27

from django.db import migrations, models
import functions.models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0007_auto_20201107_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='img',
            field=models.ImageField(default='Error', height_field=300, upload_to=functions.models.Function.img_path, width_field=200),
        ),
    ]
