# Generated by Django 3.1.3 on 2020-11-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0009_auto_20201107_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='img_alt',
            field=models.TextField(default='Wait'),
        ),
    ]
